change config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -582,6 +582,60 @@ jobs:
             - Part_Ten_nightly-build-and-test-10_TEST-*.xml
     executor:
 
+  nightly-build-and-test-11:
+    docker:
+      - image: cimg/base:stable
+    resource_class: xlarge
+    steps:
+      - checkout
+      - run:
+          name: Install Java 22
+          command: |
+            sudo apt-get update && sudo apt-get install -y wget
+            wget https://download.java.net/java/GA/jdk22/830ec9fcccef480bb3e73fb7ecafe059/36/GPL/openjdk-22_linux-x64_bin.tar.gz
+            sudo mkdir -p /usr/lib/jvm
+            sudo tar zxvf openjdk-22_linux-x64_bin.tar.gz -C /usr/lib/jvm
+            sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-22/bin/java 2200
+            sudo update-alternatives --config java
+            echo 'export PATH="/usr/lib/jvm/jdk-22/bin:$PATH"' >> $BASH_ENV
+            source $BASH_ENV
+            java -version
+      - run:
+          name: Install Maven
+          command: |
+            sudo apt-get install -y maven
+            mvn -version
+      - run:
+          name: Install Chrome
+          command: |
+            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
+            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
+            sudo apt-get update
+            sudo apt-get install -y google-chrome-stable
+            google-chrome --version
+      - run:
+          name: Build and run nightly tests
+          command: mvn clean test "-Dsurefire.suiteXmlFiles=regression11.xml" "-Drun.headless=true" "-Dtest.env=stag" || true
+      - store_artifacts:
+          path: target/surefire-reports
+          destination: daily-build-and-test-artifacts-11
+      - run:
+          name: Verify Test Results Exist
+          command: ls -R target/surefire-reports || echo "Test results missing!"
+      - run:
+          name: Copy test results to workspace
+          command: |
+            mkdir -p ~/workspace
+            PART_NAME="Part_Eleven"
+            for file in target/surefire-reports/TEST-*.xml; do
+              [ -f "$file" ] && cp "$file" ~/workspace/${PART_NAME}_nightly-build-and-test-11_$(basename "$file")
+            done
+      - persist_to_workspace:
+          root: ~/workspace
+          paths:
+            - Part_Eleven_nightly-build-and-test-11_TEST-*.xml
+    executor:
+
   daily-build-and-test-1:
     docker:
       - image: cimg/base:stable
@@ -1122,6 +1176,59 @@ jobs:
             - Part_Ten_daily-build-and-test-10_TEST-*.xml
     executor:
 
+  daily-build-and-test-11:
+    docker:
+      - image: cimg/base:stable
+    resource_class: xlarge
+    steps:
+      - checkout
+      - run:
+          name: Install Java 22
+          command: |
+            sudo apt-get update && sudo apt-get install -y wget
+            wget https://download.java.net/java/GA/jdk22/830ec9fcccef480bb3e73fb7ecafe059/36/GPL/openjdk-22_linux-x64_bin.tar.gz
+            sudo mkdir -p /usr/lib/jvm
+            sudo tar zxvf openjdk-22_linux-x64_bin.tar.gz -C /usr/lib/jvm
+            sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-22/bin/java 2200
+            sudo update-alternatives --config java
+            echo 'export PATH="/usr/lib/jvm/jdk-22/bin:$PATH"' >> $BASH_ENV
+            source $BASH_ENV
+            java -version
+      - run:
+          name: Install Maven
+          command: |
+            sudo apt-get install -y maven
+            mvn -version
+      - run:
+          name: Install Chrome
+          command: |
+            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
+            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
+            sudo apt-get update
+            sudo apt-get install -y google-chrome-stable
+            google-chrome --version
+      - run:
+          name: Build and run daily tests
+          command: mvn clean test "-Dsurefire.suiteXmlFiles=regression11.xml" "-Drun.headless=true" "-Dtest.env=stag" "-Dcreate.cycle=true" || true
+      - store_artifacts:
+          path: target/surefire-reports
+          destination: daily-build-and-test-artifacts-11
+      - run:
+          name: Verify Test Results Exist
+          command: ls -R target/surefire-reports || echo "Test results missing!"
+      - run:
+          name: Copy test results to workspace
+          command: |
+            mkdir -p ~/workspace
+            PART_NAME="Part_Eleven"
+            for file in target/surefire-reports/TEST-*.xml; do
+              [ -f "$file" ] && cp "$file" ~/workspace/${PART_NAME}_daily-build-and-test-11_$(basename "$file")
+            done
+      - persist_to_workspace:
+          root: ~/workspace
+          paths:
+            - Part_Eleven_daily-build-and-test-11_TEST-*.xml
+    executor:
 
   calculate-pass-fail-rate:
     docker:
@@ -1307,6 +1414,7 @@ workflows:
       - nightly-build-and-test-8
       - nightly-build-and-test-9
       - nightly-build-and-test-10
+      - nightly-build-and-test-11
       - calculate-pass-fail-rate:
           requires:
             - nightly-build-and-test-6
@@ -1314,6 +1422,7 @@ workflows:
             - nightly-build-and-test-8
             - nightly-build-and-test-9
             - nightly-build-and-test-10
+            - nightly-build-and-test-11
 
 
   scheduled-test-2:
@@ -1352,6 +1461,7 @@ workflows:
       - daily-build-and-test-8
       - daily-build-and-test-9
       - daily-build-and-test-10
+      - daily-build-and-test-11
 #      - calculate-pass-fail-rate:
 #          requires:
 #            - daily-build-and-test-6
@@ -1359,3 +1469,4 @@ workflows:
 #            - daily-build-and-test-8
 #            - daily-build-and-test-9
 #            - daily-build-and-test-10
+#            - daily-build-and-test-11
